name: Grid India Scraper

on:
  workflow_dispatch:

  schedule:
    # Runs every day at 2:00 AM UTC
    - cron: '0 2 * * *'

jobs:
  scrape:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Verify Chrome
      #   run: |
      #     google-chrome --version

      - name: Run Scraper
        run: |
          python scraper.py
